### ISSUE TITLE
Proposal Feedback

### ISSUE THREAD

**Issue by eshoule** [Meenakshi-Anand/Facebook-Clone#1]
## MVPs
- [x] Add a descriptive sentence of the app.
- [x] Add estimations of how long it will take to code each MVP.
- [x] Add the following to each MVP
  * "Adequate styling"
  * "Smooth, bug-free navigation"
  * "Seeded with info to demonstrate this feature"
- [x] Switch Hosting on Heroku and New account creation/login so you have something to host on Heroku.
---

## Schema
- [x] Re-do all of your tables in markdown with appropriate formatting.
- [x] Add default false to your approval_status column details.
- [x] You may want a wall_id in your posts table to track where it was posted.
- [x] Add bullet points after each table that state which foreign keys will reference to which table or references to the associations that will be made.

## State Shape
- [x] Re-do all of your state shape in markdown with appropriate formatting. Ensure all keys are camelCased.
- [x] Normalize your state shape to reflect this documentation/standard https://redux.js.org/recipes/structuring-reducers/normalizing-state-shape#relationships-and-tables. The bluebird example is good to follow when normalizing the state shape (https://github.com/appacademy/bluebird/).

## Routes
- [x] Re-format so they have the same styling as the examples (inline coding text, font size, etc.)
- [x] Add descriptions to your frontend routes.

## Wireframes
- [x] Re-format - component names should be displayed with ```inline coding text```.
- [x] Add routes and state information for each wireframe. Follow this example https://github.com/appacademy/bluebird/wiki/component-hierarchy

**Comment by Meenakshi-Anand** [comment]
Hi Liz,
I have made the necessary changes.

**Comment by eshoule** [comment]
Everything looks great! I will close the issue.
