### ISSUE TITLE
PA Review User Authentication

### ISSUE THREAD

**Issue by Meenakshi-Anand** [Meenakshi-Anand/Facebook-Clone#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [ ] Adequate and appropriate seeds

**Comment by eshoule** [comment]
Good job! Definitely try to style your error messages, but concentrate on other MVPs for now.
