### ISSUE TITLE
PA-Review Friending

### ISSUE THREAD

**Issue by Meenakshi-Anand** [Meenakshi-Anand/Facebook-Clone#4]
- [ ] Logged in users can send add a friend request to other users.
- [ ] Logged in user can accept a friend request .
- [ ] Logged in user can post in his friends wall.
- [ ] Adequate styling
- [ ] Smooth, bug-free navigation
- [ ] Seeded with info to demonstrate this feature

**Comment by eshoule** [comment]
Good job. Make the following changes, and I will close the issue.

- [ ] Seed a lot more data into your app.
- [ ] The friend friend request count notification does not hover over the friend request dropdown. It is floating to the far right. Change it to hover over the friend request dropdown.
- [ ] Fix styling in general - the posts container exceeds the width of the rest of the page, the profile picture covers the timeline button, the add friend button is also outside the page width to the far right of the banner photo, etc.

**Comment by Meenakshi-Anand** [comment]
Fixed the issues
